# Test against the latest version of this Node.js version
environment:
  nodejs_version: '8'

skip_commits:
  message: /chore/

skip_tags: true
skip_branch_with_pr: true

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install
  
  
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm run lint

notifications:
  - provider: Slack
    incoming_webhook:
      secure: JhngXiwYl7JkEO7bo4Fh1k6rOy+lZ3dFxGFI4FL3Iep6ruC4WVIj35Px/jzc4Xi0GbEAGTjRQi8NZg4s0V0zZGn3IMRp+HNRdMzmh/Y492s=
    channel: '#build-success'
    on_build_success: true
    on_build_failure: false
    on_build_status_changed: false
    template: '<{{buildUrl}}|Build [{{projectName}}] {{buildVersion}} {{status}}> Commit <{{commitUrl}}|{{commitId}}> by {{commitAuthor}} on {{commitDate}}: _{{commitMessage}}_'
  - provider: Slack
    incoming_webhook:
      secure: JhngXiwYl7JkEO7bo4Fh1k6rOy+lZ3dFxGFI4FL3IeqzmMP5SvRSku5VvYel8VEXyavmuo/izODp6H0mjj4tSZhumWBkfENV0JNN+W6Kss8=
    channel: '#build-failed'
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: false
    template: '<{{buildUrl}}|Build [{{projectName}}] {{buildVersion}} {{status}}> Commit <{{commitUrl}}|{{commitId}}> by {{commitAuthor}} on {{commitDate}}: _{{commitMessage}}_'


configuration: Debug

# here we are going to override common configuration
for:

# override settings for `master` branch
-
  branches:
    only:
      - master

  configuration: Release

test_script:
  - npm whoami  
  - git checkout -q master       
  - git config --global credential.helper store
  - ps: Add-Content "$HOME\.git-credentials" "https://$($env:git_access_token):x-oauth-basic@github.com`n"
  - git config user.email "aaron-drabeck@leavitt.com"
  - git config user.name "AppVeyor Automation"
  - ps: '"//registry.npmjs.org/:_authToken=$env:npm_auth_token`n" | out-file "$env:userprofile\.npmrc" -Encoding ASCII'
  - npm run lerna:publish

# Don't actually build.
build: off

