export const HTTPStatusCodes = new Map<number, string>();
HTTPStatusCodes.set(200, 'OK');
HTTPStatusCodes.set(201, 'Created');
HTTPStatusCodes.set(202, 'Accepted');
HTTPStatusCodes.set(203, 'Non-Authoritative Information');
HTTPStatusCodes.set(204, 'No Content');
HTTPStatusCodes.set(205, 'Reset Content');
HTTPStatusCodes.set(206, 'Partial Content');
HTTPStatusCodes.set(300, 'Multiple Choices');
HTTPStatusCodes.set(301, 'Moved Permanently');
HTTPStatusCodes.set(302, 'Found');
HTTPStatusCodes.set(303, 'See Other');
HTTPStatusCodes.set(304, 'Not Modified');
HTTPStatusCodes.set(305, 'Use Proxy');
HTTPStatusCodes.set(306, 'Unused');
HTTPStatusCodes.set(307, 'Temporary Redirect');
HTTPStatusCodes.set(400, 'Bad Request');
HTTPStatusCodes.set(401, 'Unauthorized');
HTTPStatusCodes.set(402, 'Payment Required');
HTTPStatusCodes.set(403, 'Forbidden');
HTTPStatusCodes.set(404, 'Not Found');
HTTPStatusCodes.set(405, 'Method Not Allowed');
HTTPStatusCodes.set(406, 'Not Acceptable');
HTTPStatusCodes.set(407, 'Proxy Authentication Required');
HTTPStatusCodes.set(408, 'Request Timeout');
HTTPStatusCodes.set(409, 'Conflict');
HTTPStatusCodes.set(410, 'Gone');
HTTPStatusCodes.set(411, 'Length Required');
HTTPStatusCodes.set(412, 'Precondition Required');
HTTPStatusCodes.set(413, 'Request Entry Too Large');
HTTPStatusCodes.set(414, 'Request-URI Too Long');
HTTPStatusCodes.set(415, 'Unsupported Media Type');
HTTPStatusCodes.set(416, 'Requested Range Not Satisfiable');
HTTPStatusCodes.set(417, 'Expectation Failed');
HTTPStatusCodes.set(418, "I'm a teapot");
HTTPStatusCodes.set(429, 'Too Many Requests');
HTTPStatusCodes.set(500, 'Internal Server Error');
HTTPStatusCodes.set(501, 'Not Implemented');
HTTPStatusCodes.set(502, 'Bad Gateway');
HTTPStatusCodes.set(503, 'Service Unavailable');
HTTPStatusCodes.set(504, 'Gateway Timeout');
HTTPStatusCodes.set(505, 'HTTP Version Not Supported');
