# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'    
          scope: leavittsoftware    
    
    - name: Install
      run: npm install
    
    - name: Configure CI Git User
      run: | 
          git config --global user.email automation@leavitt.com
          git config --global user.name 'GitHub Actions'
          npm whoami
      env:
          USER_NAME: ${{ secrets.DEPLOYING_USER_NAME }}
          GITHUB_PAT: ${{ secrets.PAT }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
                   
    - name: Lint
      run: npm run lint           
    
    - name: Run Lerna Publish
      run: npm run lerna:publish
      env:
         GH_TOKEN: ${{ secrets.PAT }}
         GITHUB_TOKEN: ${{ secrets.PAT }}
         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
         
        
